FotoJoin\ControlPanelBundle\Entity\Album:
    type: entity
    table: Album
    manyToOne:
#        author:
#            targetEntity: FotoJoin\UserBundle\Entity\Author
        user:
            targetEntity: FotoJoin\UserBundle\Entity\User
            inversedBy: albums
    oneToMany:
        photographies:
            targetEntity: FotoJoin\ControlPanelBundle\Entity\Photography
            mappedBy: album
            cascade: [persist, merge, remove]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    lifecycleCallbacks: {  }
