FotoJoin\UserBundle\Entity\Message:
    type: entity
    table: Message
    repositoryClass: FotoJoin\UserBundle\Entity\MessageRepository
    manyToOne:
        sender:
            targetEntity: FotoJoin\UserBundle\Entity\User
        recipient:
            targetEntity: FotoJoin\UserBundle\Entity\User
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        type:
            type: integer
            nullable: true
        content:
            type: text
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }
