admin_appraisement_index:
    path:     /
    defaults: { _controller: "FotoJoinAdminBundle:Appraisement:index" }
    methods:  GET

admin_appraisement_show:
    path:     /{id}/show
    defaults: { _controller: "FotoJoinAdminBundle:Appraisement:show" }
    methods:  GET

admin_appraisement_new:
    path:     /new
    defaults: { _controller: "FotoJoinAdminBundle:Appraisement:new" }
    methods:  [GET, POST]

admin_appraisement_edit:
    path:     /{id}/edit
    defaults: { _controller: "FotoJoinAdminBundle:Appraisement:edit" }
    methods:  [GET, POST]

admin_appraisement_delete:
    path:     /{id}/delete
    defaults: { _controller: "FotoJoinAdminBundle:Appraisement:delete" }
    methods:  [GET, DELETE]
