datetime_index:
    path:     /
    defaults: { _controller: "FotoJoinAdminBundle:Datetime:index" }
    methods:  GET

datetime_show:
    path:     /{id}/show
    defaults: { _controller: "FotoJoinAdminBundle:Datetime:show" }
    methods:  GET

datetime_new:
    path:     /new
    defaults: { _controller: "FotoJoinAdminBundle:Datetime:new" }
    methods:  [GET, POST]

datetime_edit:
    path:     /{id}/edit
    defaults: { _controller: "FotoJoinAdminBundle:Datetime:edit" }
    methods:  [GET, POST]

datetime_delete:
    path:     /{id}/delete
    defaults: { _controller: "FotoJoinAdminBundle:Datetime:delete" }
    methods:  DELETE
