admin_plan_index:
    path:     /
    defaults: { _controller: "FotoJoinAdminBundle:Plan:index" }
    methods:  GET

admin_plan_show:
    path:     /{id}/show
    defaults: { _controller: "FotoJoinAdminBundle:Plan:show" }
    methods:  GET

admin_plan_new:
    path:     /new
    defaults: { _controller: "FotoJoinAdminBundle:Plan:new" }
    methods:  [GET, POST]

admin_plan_edit:
    path:     /{id}/edit
    defaults: { _controller: "FotoJoinAdminBundle:Plan:edit" }
    methods:  [GET, POST]

admin_plan_delete:
    path:     /{id}/delete
    defaults: { _controller: "FotoJoinAdminBundle:Plan:delete" }
    methods:  [GET, DELETE]
