gus_uploader:
    media_class: Uni\AdminBundle\Entity\Media
    uploads_dir: 'uploads/'
    settings:
        upload_dir: 'files/'
        upload_url: '/files/'
        user_dirs: false
        download_via_php: false
        accept_file_types: '/.+$/i'
        inline_file_types: '/\.(gif|jpe?g|png)$/i'
        print_response: true
        mkdir_mode: 0755
        readfile_chunk_size: 10485760
        max_file_size: null
        min_file_size: 1
        max_number_of_files: null
        correct_image_extensions: false
        max_width: null
        max_height: null
        min_width: 1
        min_height: 1
        discard_aborted_uploads: true
        image_library: 1
        image_versions:
            original:
                auto_orient: true
#            medium:
#                max_width: 800
#                max_height: 600
            thumbnail:
#                crop: false
                max_width: 80
                max_height: 80