hwi_oauth:
    #connect:
        #account_connector: fotojoin.user_provider
    firewall_names:
        - 'main' # name of security firewall configured to work with HWIOAuthBundle
    fosub:
        username_iterations: 30
        properties:
            facebook:    facebookid
    resource_owners:
        facebook:
            type: facebook
            client_id: '127814224492163'
            client_secret: 'fb164f697e187bd9c74ed2235ed6c18d'
            scope: email
            infos_url: https://graph.facebook.com/me?fields=id,name,email,first_name,last_name,gender
        google:
            type: google
            client_id: '487809298108-utsg239g8siij8fast8ncvgvqq26pfc9.apps.googleusercontent.com'
            client_secret: 'qlASIGKQr8JuMJdRARiOGklB'
            scope: email
        twitter:
            type: twitter
            client_id: 'EAlJkN8QKXvEpiSim7hpShaYk'
            client_secret: '7c6Fg4blkkYoRErdsbfb8iQ463zFzT8sJk6RdCuLrBsMkn0eSP'
            scope: "email" 
            paths:
                email: email
            options:
                include_email: true