# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

#    access_denied_url:    ~
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
#        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_AUTHOR:      ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [in_memory, fotojoin_userbundle]
        in_memory:
            memory:
                users:
                    root: { password: Au0ZedG4Ewn5aOK, roles: 'ROLE_ADMIN' }
        fotojoin_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            form_login:
                login_path: /login
                failure_path: /login
                check_path: /login_check
                always_use_default_target_path: true
                default_target_path: /panel/status
                provider: fotojoin_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:   /logout
                target: /login
            oauth:
                login_path:        /login
                failure_path:      /login
                default_target_path: /gallery/join
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                    twitter:             "/login/check-twitter"
                use_forward:       false
                oauth_user_provider:
#                    service: hwi_oauth.user.provider.fosub_bridge
                    service: fotojoin.user_provider


    access_control:
        - { path: ^/gallery, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/gallery/join, roles: [ROLE_ADMIN] }
        - { path: ^/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/register, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/resetting, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/panel, roles: [ROLE_USER] }
        - { path: ^/panel/photography/, roles: [ROLE_AUTHOR] }
        - { path: ^/admin, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        # Include the following line to also secure the /admin path itself
