# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - :Form:bootstrap.html.twig
            - :Form:vich.html.twig
            - :Form:profilephoto.html.twig
            - :Form:photography.html.twig
    globals:
        user_level: "%user_level%"
        contact_reason: "%contact_reason%"