fos_user_profile_show:
    path:     /
    defaults: { _controller: "FotoJoinUserBundle:Profile:show" }

fos_user_profile_edit:
    path:     /edit
    defaults: { _controller: "FotoJoinUserBundle:Profile:edit" }
    methods: [GET|POST]

fos_user_upgrade:
    path:     /upgrade
    defaults: { _controller: "FotoJoinUserBundle:Profile:upgrade" }
    methods: [GET|POST]
