<?php

namespace FotoJoin\AdminBundle\Entity;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCities()
    {
        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c')
            ->from('FotoJoinAdminBundle:City', 'c')
            ->leftJoin('FotoJoinUserBundle:User', 'u', 'WITH', 'u.city1 = c.id OR u.city2 = c.id OR u.city3 = c.id')
            ->join('u.photographies', 'ph')
            ->groupBy('c.id')
        ;

        return $qb;
    }
}
