<?php

namespace FotoJoin\AdminBundle\Entity;

/**
 * ProvinceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProvinceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActive($region)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()->select('p')
            ->from('FotoJoinAdminBundle:Province', 'p')
            ->join('p.communes', 'c')
            ->join('c.users', 'u')
            ->join('u.albums', 'a')
            ->join('a.photographies', 'ph')
            ->where('p.region = :region')
            ->groupBy('p.id')
            ->setParameter('region', $region)
        ;

        return $qb->getQuery()->getResult();
    }
}
