FotoJoin\AdminBundle\Entity\Province:
    type: entity
    table: admin_province
    repositoryClass: FotoJoin\AdminBundle\Entity\ProvinceRepository
    manyToOne:
        region:
            targetEntity: FotoJoin\AdminBundle\Entity\Region
            inversedBy: provinces
    oneToMany:
        communes:
            targetEntity: FotoJoin\AdminBundle\Entity\Commune
            mappedBy: province
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 100
    lifecycleCallbacks: {  }
