<?php

namespace FotoJoin\GalleryBundle\Entity;

/**
 * AppraisementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppraisementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getJoinPointsByUser($user)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('COUNT(DISTINCT ap.id) as quantity', 'SUM(ap.score) as score')
            ->from('FotoJoinGalleryBundle:Appraisement', 'ap')
            ->where('ap.user = :user')
            ->setParameters(array('user' => $user));

        $joinPoints = $qb
            ->getQuery()
            ->getSingleResult();

        return $joinPoints;
    }

    public function getPhotoPointsByUser($user)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb
            ->select('COUNT(DISTINCT ap.id) as quantity', 'SUM(ap.score) as score', 'AVG(ap.value) as average')
            ->from('FotoJoinGalleryBundle:Appraisement', 'ap')
            ->join('ap.photography', 'ph')
            ->join('ph.user', 'u')
            ->where('u.id = :user')
            ->setParameters(array('user' => $user));

        $photoPoints = $qb
            ->getQuery()
            ->getSingleResult();

        return $photoPoints;
    }
}
