foto_join_admin_city:
    resource: "@FotoJoinAdminBundle/Resources/config/routing/city.yml"
    prefix:   /city

foto_join_admin_category:
    resource: "@FotoJoinAdminBundle/Resources/config/routing/category.yml"
    prefix:   /category

foto_join_admin_dashboard:
    resource: "@FotoJoinAdminBundle/Resources/config/routing/dashboard.yml"
    prefix:   /dashboard

foto_join_admin_root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/dashboard
        permanent: true
