foto_join_admin_user:
    resource: "@FotoJoinAdminBundle/Resources/config/routing/user.yml"
    prefix:   /user

foto_join_admin_photography:
    resource: "@FotoJoinAdminBundle/Resources/config/routing/photography.yml"
    prefix:   /photography

foto_join_admin_album:
    resource: "@FotoJoinAdminBundle/Resources/config/routing/album.yml"
    prefix:   /album

foto_join_admin_appraisement:
    resource: "@FotoJoinAdminBundle/Resources/config/routing/appraisement.yml"
    prefix:   /appraisement

foto_join_admin_city:
    resource: "@FotoJoinAdminBundle/Resources/config/routing/city.yml"
    prefix:   /city

foto_join_admin_category:
    resource: "@FotoJoinAdminBundle/Resources/config/routing/category.yml"
    prefix:   /category

foto_join_admin_dashboard:
    resource: "@FotoJoinAdminBundle/Resources/config/routing/dashboard.yml"
    prefix:   /dashboard

foto_join_admin_root:
    path:     /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /admin/dashboard
        permanent: true
