FotoJoin\UserBundle\Entity\User:
    properties:
    # Your custom fields in your user entity, here is an example with FirstName
        name:
            - NotBlank:
                message: fotojoin_user.first_name.blank
                groups: [ "FotoJoinProfile" ]
            - Length:
                min: 2
                minMessage: fotojoin_user.first_name.short
                max: 255
                maxMessage: fotojoin_user.first_name.long
                groups: [ "FotoJoinProfile" ]



# Note: We still want to validate the email
# See FOSUserBundle/Resources/config/validation/orm.xml to understand
# the UniqueEntity constraint that was originally applied to both
# username and email fields
#
# As you can see, we are only applying the UniqueEntity constraint to 
# the email field and not the username field.
FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
             fields: email
             errorPath: email 
             message: fos_user.email.already_used
             groups: [ "FotoJoinRegistration", "FotoJoinProfile" ]

    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "FotoJoinRegistration", "FotoJoinProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "FotoJoinRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "FotoJoinRegistration", "FotoJoinProfile" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "FotoJoinRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                max: 4096
                minMessage: fos_user.password.short
                groups: [ "FotoJoinRegistration", "FotoJoinProfile", "ResetPassword", "ChangePassword"]

FOS\UserBundle\Model\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "FotoJoinRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "FotoJoinRegistration" ]

FOS\UserBundle\Propel\User:
    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "FotoJoinRegistration", "FotoJoinProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "FotoJoinRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "FotoJoinRegistration", "FotoJoinProfile" ]

        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "FotoJoinRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                max: 4096
                minMessage: fos_user.password.short
                groups: [ "FotoJoinRegistration", "FotoJoinProfile", "ResetPassword", "ChangePassword"]


FOS\UserBundle\Propel\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "FotoJoinRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "FotoJoinRegistration" ]